/* example.c generated by valac 0.46.6, the Vala compiler
 * generated from example.vala, do not modify */

#include <glib.h>

gint __attribute__((visibility("default"))) boo (void);

gint
__attribute__((visibility("default"))) boo (void)
{
	gint result = 0;
	result = 42;
	return result;
}

